env:
  es2021: true
plugins:
  - "@nativescript"
extends:
  - plugin:svelte/recommended
  - "plugin:@nativescript/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  extraFileExtensions: ['.svelte']
overrides:
  - files: ['*.svelte']
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
rules: {}
